### ISSUE TITLE
UnboundLocalError when change 'token_encoding' in parameter to 'char'

### ISSUE THREAD

**Issue by ghost** [iliaschalkidis/ELMo-keras#5]
hi ,first of all thanks for implementation. but the question is when i change `token_encoding` in parameters from `word` to `char` , it gives below error:

`
File "/path/to/ELMo-keras/elmo/model.py", line 162, in compile_elmo
    tied_to=embeddings if self.parameters['weight_tying'] else None)
UnboundLocalError: local variable 'embeddings' referenced before assignment
`

aren't your code still support character embedding ?

**Comment by dilaratorunoglu** [comment]
Hello, I also would like to thank you for the implementation. 
I run your code with token_encoding model in "word" model and it works perfectly fine, but I wanted to change it to "char" model and I have the same error.

**"File "/path/to/ELMo-keras/elmo/model.py", line 162, in compile_elmo tied_to=embeddings if self.parameters['weight_tying'] else None) UnboundLocalError: local variable 'embeddings' referenced before assignment"**

Do you know how to fix this problem? Because I would also want to train my model with character embedding as well.

Thank you,

**Comment by iliaschalkidis** [comment]
Hi @masepehr and @dilaratorunoglu,

Thanks for reporting this back to me. This issue was more like a mis-configuration rather than an actual bug. Anyway it's my fault, I should have made that clear.

**Why combing the parameters `"token_encoding": "word"` with  `"weight_tying": True` is not valid?**

When you define the parameters in train_demo.py, you cannot have `"token_encoding": "word"` and  `"weight_tying": True` at the same time. Weight tying means that you actually tie the word embeddings matrix, which is only been used `"token_encoding": "word"` with the weight matrix of the output layer. If you do not use `"token_encoding": "word"`, there is no a word embeddings matrix at all order to tie up with the output layer, because `"token_encoding": "char"` means that you opted to train char-based representations.

Anyhow, I updated the if case in lines (160-161) in order to prevent this issue even if someone accidentally forgets to set `"weight_tying": False` when he uses `"token_encoding": "char"`  https://github.com/iliaschalkidis/ELMo-keras/blob/81d8bc65cd00b27d3a7560397838b3378a8ce4e2/elmo/model.py#L160
https://github.com/iliaschalkidis/ELMo-keras/blob/81d8bc65cd00b27d3a7560397838b3378a8ce4e2/elmo/model.py#L161

Let me know, if you have any further issues, cheers!

**Comment by dilaratorunoglu** [comment]
Thank you so much, I will try this change and let you know if any other problems occur, thank you for your fast reply!

**Comment by ghost** [comment]
> Hi @masepehr and @dilaratorunoglu,
> 
> Thanks for reporting this back to me. This issue was more like a mis-configuration rather than an actual bug. Anyway it's my fault, I should have made that clear.
> 
> **Why combing the parameters `"token_encoding": "word"` with `"weight_tying": True` is not valid?**
> 
> When you define the parameters in train_demo.py, you cannot have `"token_encoding": "word"` and `"weight_tying": True` at the same time. Weight tying means that you actually tie the word embeddings matrix, which is only been used `"token_encoding": "word"` with the weight matrix of the output layer. If you do not use `"token_encoding": "word"`, there is no a word embeddings matrix at all order to tie up with the output layer, because `"token_encoding": "char"` means that you opted to train char-based representations.
> 
> Anyhow, I updated the if case in lines (160-161) in order to prevent this issue even if someone accidentally forgets to set `"weight_tying": False` when he uses `"token_encoding": "char"`
> 
> https://github.com/iliaschalkidis/ELMo-keras/blob/81d8bc65cd00b27d3a7560397838b3378a8ce4e2/elmo/model.py#L160
> 
> https://github.com/iliaschalkidis/ELMo-keras/blob/81d8bc65cd00b27d3a7560397838b3378a8ce4e2/elmo/model.py#L161
> 
> Let me know, if you have any further issues, cheers!

Thank you so much ! it works fine now :)

**Comment by dilaratorunoglu** [comment]
Hello again. I also changed the related code parts; however I got this error for this time:

`File "/home/.../ELMo-keras-local/elmo/lm_generator.py", line 51, in __getitem__
    word_char_indices_batch[i] = self.get_token_char_indices(sent_id=batch_id)
  File "/home/.../ELMo-keras-local/elmo/lm_generator.py", line 132, in get_token_char_indices
    if token_ids[1]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

Do you have any idea what the problem is ?

**Comment by ghost** [comment]
change this line :
`if token_ids[1]:`
to 
`if token_ids[1].all():`
